### ISSUE TITLE
JS has getters and setters for properties, don't postfix with Get and Set

### ISSUE THREAD

**Issue by kenchris** [jtguggedal/thingy_web_bluetooth#3]
Things like cloudTokenGet and loudTokenSet feel very alien in JS

Use properties in JS with setters and getters instead.

**Comment by jtguggedal** [comment]
Thanks for letting me know. Having little JS experience, I was not aware of that.

**Comment by kenchris** [comment]
Feel free to run though my JS training :-)

https://docs.google.com/presentation/d/1TtjUVLRDKQ4YPnf1CEEnKgK8b3gI78tKOzu9A9EVOiI/edit?usp=sharing

**Comment by jtguggedal** [comment]
I'll definitely go through that, I need to unlearn those C-like practices I have picked up.. :-) And thanks for reviewing the code and commenting, much appreciated!

One question about the getters and setters: Some of the properties, such as the Eddystone URL, need more than one argument (prefix, URL and postfix), which is not possible in setters. I have so far used objects to pass all three like this:
```javascript
set eddystoneUrl(params) {
...
		const prefix = params.prefix;
		const url = params.url;
		const postfix = params.postfix || null;
 
...
}
```

Is this a reasonable way of doing it, or should I split it in three different properties/setters like this?
```javascript
set eddystonePrefix(prefix) { ... }
set eddystoneUrl(url) { ... }
set eddystonePostfix(postfix) { ... }
```
Having all in one object makes the implementation a bit simpler since I don't have to read the current value and change only certain bytes, but it shouldn't be a problem to change that.
 

I have done this with some getters, such as `connParams` that returns an object with three properties (slaveLatency, minConnInterval, maxConnInterval), while there are three individual setters. Should I instead have three corresponding getters and get rid of the one that returns an object? Or should this one also use a setter with an object as parameter?

**Comment by kenchris** [comment]
In this exact same, is there any reason why you cannot use the URL object already in the platform?

https://developer.mozilla.org/en-US/docs/Web/API/URL

That the protocol compresses the URL by using some number to represent the scheme start part, is really an implementation detail which you implementation should handle. Ie. you can easily detect "https://www." and convert to the format required by Eddystone.

With postfix, I assume you are referring to the searchParams.

If people really need to set these things manually (I don't see the use-case) then that could be a more advanced API, but I think it is unneeded.

Additionally a setter can throw (check https://developer.mozilla.org/en-US/docs/Mozilla/WebIDL_bindings [SetterThrows]) so you can throw when the URL exceeds the allowed length.

URL seems to throw TypeError in case of error: https://url.spec.whatwg.org/#api so you could throw TypeError with a proper message

**Comment by kenchris** [comment]
Btw not sure if you see this, but I did a few comments inside your commits: https://github.com/jtguggedal/thingy_web_bluetooth/commits/async

**Comment by jtguggedal** [comment]
You're right, it's easier to just detect the prefix patterns and convert to corresponding code. I see in the Eddystone spec that the thing I called postfix (ie ".com", ".org") is actually called expansion codes: https://github.com/google/eddystone/tree/master/eddystone-url
They can be detected as well.

Thanks for the comments in the commits, again very useful!

**Comment by jtguggedal** [comment]
The Eddystone URL getter/setter now use the URL API so the getter now returns a `new URL(url)`. The conversion of URL scheme prefix and expansion codes per Eddystone URL specification is now done within the setter, so the only parameter it needs is a URL.

**Comment by kenchris** [comment]
Cool, then you should close this issue

**Comment by kenchris** [comment]
Why did you reopen? Because it is more general and not just related to the Eddystone?

**Comment by jtguggedal** [comment]
I'm reopening this issue as there are some issues with using async getters/setters. 
When using for example 
```javascript 
await thingy.name = "newName"
```
I get the following error: `Uncaught ReferenceError: Invalid left-hand side in assignment` for the setter. Removing the `await` keyword fixes this, but then this will cause a GATT operation error: 

```javascript 
thingy.name = "newName";
await thingy.<some async BLE operation>
```
That happens because two GATT operations can't run at the same time. I've received some feedback that methods should be used instead as accessing the Thingy properties always require async GATT operations, and that async getters/setters would feel a bit strange as they're not really a part of ES6 spec.

I'm not sure which way to go forward with this, but I will continue to test with async setters to see if there is some workaround here. I'll just keep this issue open so that anyone can feel free to come with suggestions on how to approach this as it will affect a large part of the API.

**Comment by kenchris** [comment]
Do people actually set these values one by one, or would a transactional API make more sense?

If you move back to functions, it should be ```getName()``` and ```setName``` to follow the platform.

@beaufortfrancois do you have any ideas/recommendation?

**Comment by jtguggedal** [comment]
When using `// @ts-check` in `thingy.js`, setters are not allowed to return anything there, so making them async is not possible. I'll have to move back to functions then to obey the ts-rules, which shouldn't be much of a job anyway. I'll await some more feedback if anyone else has some suggestions before I change it. I'll use the naming pattern with prefixes if I move back to functions.
